2020-05-09 20:17:19.620 [error] <0.383.0> gen_server <0.383.0> terminated with reason: {socket_error,timeout}
2020-05-09 20:17:19.658 [error] <0.378.0> gen_server <0.378.0> terminated with reason: {socket_error,timeout}
2020-05-09 20:17:21.521 [error] <0.378.0> CRASH REPORT Process <0.378.0> with 0 neighbours exited with reason: {socket_error,timeout} in gen_server:handle_common_reply/8 line 751
2020-05-09 20:17:21.555 [error] <0.376.0> Supervisor {<0.376.0>,amqp_connection_sup} had child connection started with amqp_gen_connection:start_link(<0.377.0>, {amqp_params_network,<<"guest">>,<<"jwCOBLkSqFXmiA+/vmtiUa9vznwLqAgnQSnsmwvu0+F5W4PjzlQHi/WgVNwAnq...">>,...}) at <0.378.0> exit with reason {socket_error,timeout} in context child_terminated
2020-05-09 20:17:21.556 [error] <0.376.0> Supervisor {<0.376.0>,amqp_connection_sup} had child connection started with amqp_gen_connection:start_link(<0.377.0>, {amqp_params_network,<<"guest">>,<<"jwCOBLkSqFXmiA+/vmtiUa9vznwLqAgnQSnsmwvu0+F5W4PjzlQHi/WgVNwAnq...">>,...}) at <0.378.0> exit with reason reached_max_restart_intensity in context shutdown
2020-06-06 22:02:30.336 [error] <0.663.0> gen_server <0.663.0> terminated with reason: #{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError',message => <<"connect raised KeyError exception: key :database not found. The exception details are hidden, as they may contain sensitive data such as database credentials. You may set :show_sensitive_data_on_connection_error to true when starting your connection if you wish to see all of the details">>} in 'Elixir.Keyword':'fetch!'/2 line 399
2020-06-06 22:02:30.336 [error] <0.664.0> gen_server <0.664.0> terminated with reason: #{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError',message => <<"connect raised KeyError exception: key :database not found. The exception details are hidden, as they may contain sensitive data such as database credentials. You may set :show_sensitive_data_on_connection_error to true when starting your connection if you wish to see all of the details">>} in 'Elixir.Keyword':'fetch!'/2 line 399
2020-06-06 22:02:30.336 [error] <0.665.0> gen_server <0.665.0> terminated with reason: #{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError',message => <<"connect raised KeyError exception: key :database not found. The exception details are hidden, as they may contain sensitive data such as database credentials. You may set :show_sensitive_data_on_connection_error to true when starting your connection if you wish to see all of the details">>} in 'Elixir.Keyword':'fetch!'/2 line 399
2020-06-06 22:02:30.336 [error] <0.666.0> gen_server <0.666.0> terminated with reason: #{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError',message => <<"connect raised KeyError exception: key :database not found. The exception details are hidden, as they may contain sensitive data such as database credentials. You may set :show_sensitive_data_on_connection_error to true when starting your connection if you wish to see all of the details">>} in 'Elixir.Keyword':'fetch!'/2 line 399
2020-06-06 22:02:30.336 [error] <0.665.0> CRASH REPORT Process <0.665.0> with 0 neighbours exited with reason: #{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError',message => <<"connect raised KeyError exception: key :database not found. The exception details are hidden, as they may contain sensitive data such as database credentials. You may set :show_sensitive_data_on_connection_error to true when starting your connection if you wish to see all of the details">>} in 'Elixir.Keyword':'fetch!'/2 line 399 in 'Elixir.Connection':enter_stop/5 line 686
2020-06-06 22:02:30.336 [error] <0.667.0> gen_server <0.667.0> terminated with reason: #{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError',message => <<"connect raised KeyError exception: key :database not found. The exception details are hidden, as they may contain sensitive data such as database credentials. You may set :show_sensitive_data_on_connection_error to true when starting your connection if you wish to see all of the details">>} in 'Elixir.Keyword':'fetch!'/2 line 399
2020-06-06 22:02:30.336 [error] <0.668.0> gen_server <0.668.0> terminated with reason: #{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError',message => <<"connect raised KeyError exception: key :database not found. The exception details are hidden, as they may contain sensitive data such as database credentials. You may set :show_sensitive_data_on_connection_error to true when starting your connection if you wish to see all of the details">>} in 'Elixir.Keyword':'fetch!'/2 line 399
2020-06-06 22:02:30.337 [error] <0.637.0> gen_server <0.637.0> terminated with reason: #{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError',message => <<"connect raised KeyError exception: key :database not found. The exception details are hidden, as they may contain sensitive data such as database credentials. You may set :show_sensitive_data_on_connection_error to true when starting your connection if you wish to see all of the details">>} in 'Elixir.Keyword':'fetch!'/2 line 399
2020-06-06 22:02:30.337 [error] <0.669.0> gen_server <0.669.0> terminated with reason: #{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError',message => <<"connect raised KeyError exception: key :database not found. The exception details are hidden, as they may contain sensitive data such as database credentials. You may set :show_sensitive_data_on_connection_error to true when starting your connection if you wish to see all of the details">>} in 'Elixir.Keyword':'fetch!'/2 line 399
2020-06-06 22:02:30.337 [error] <0.670.0> gen_server <0.670.0> terminated with reason: #{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError',message => <<"connect raised KeyError exception: key :database not found. The exception details are hidden, as they may contain sensitive data such as database credentials. You may set :show_sensitive_data_on_connection_error to true when starting your connection if you wish to see all of the details">>} in 'Elixir.Keyword':'fetch!'/2 line 399
2020-06-06 22:02:30.337 [error] <0.671.0> gen_server <0.671.0> terminated with reason: #{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError',message => <<"connect raised KeyError exception: key :database not found. The exception details are hidden, as they may contain sensitive data such as database credentials. You may set :show_sensitive_data_on_connection_error to true when starting your connection if you wish to see all of the details">>} in 'Elixir.Keyword':'fetch!'/2 line 399
2020-06-06 22:02:30.337 [error] <0.638.0> gen_server <0.638.0> terminated with reason: #{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError',message => <<"connect raised KeyError exception: key :database not found. The exception details are hidden, as they may contain sensitive data such as database credentials. You may set :show_sensitive_data_on_connection_error to true when starting your connection if you wish to see all of the details">>} in 'Elixir.Keyword':'fetch!'/2 line 399
2020-06-06 22:02:30.337 [error] <0.672.0> gen_server <0.672.0> terminated with reason: #{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError',message => <<"connect raised KeyError exception: key :database not found. The exception details are hidden, as they may contain sensitive data such as database credentials. You may set :show_sensitive_data_on_connection_error to true when starting your connection if you wish to see all of the details">>} in 'Elixir.Keyword':'fetch!'/2 line 399
2020-06-06 22:02:30.337 [error] <0.662.0> Supervisor {<0.662.0>,'Elixir.DBConnection.ConnectionPool.Pool'} had child {'Elixir.Postgrex.Protocol',<0.661.0>,3} started with 'Elixir.DBConnection.Connection':start_link('Elixir.Postgrex.Protocol', [{pool_index,3},{types,'Elixir.Postgrex.DefaultTypes'},{hostname,<<"localhost">>},{port,5432},{repo,...},...], <0.661.0>, #Ref<0.1871405841.752746497.194845>) at <0.665.0> exit with reason #{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError',message => <<"connect raised KeyError exception: key :database not found. The exception details are hidden, as they may contain sensitive data such as database credentials. You may set :show_sensitive_data_on_connection_error to true when starting your connection if you wish to see all of the details">>} in 'Elixir.Keyword':'fetch!'/2 line 399 in context child_terminated
2020-06-06 22:02:30.338 [error] <0.667.0> CRASH REPORT Process <0.667.0> with 0 neighbours exited with reason: #{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError',message => <<"connect raised KeyError exception: key :database not found. The exception details are hidden, as they may contain sensitive data such as database credentials. You may set :show_sensitive_data_on_connection_error to true when starting your connection if you wish to see all of the details">>} in 'Elixir.Keyword':'fetch!'/2 line 399 in 'Elixir.Connection':enter_stop/5 line 686
2020-06-06 22:02:30.338 [error] <0.669.0> CRASH REPORT Process <0.669.0> with 0 neighbours exited with reason: #{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError',message => <<"connect raised KeyError exception: key :database not found. The exception details are hidden, as they may contain sensitive data such as database credentials. You may set :show_sensitive_data_on_connection_error to true when starting your connection if you wish to see all of the details">>} in 'Elixir.Keyword':'fetch!'/2 line 399 in 'Elixir.Connection':enter_stop/5 line 686
2020-06-06 22:02:30.338 [error] <0.670.0> CRASH REPORT Process <0.670.0> with 0 neighbours exited with reason: #{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError',message => <<"connect raised KeyError exception: key :database not found. The exception details are hidden, as they may contain sensitive data such as database credentials. You may set :show_sensitive_data_on_connection_error to true when starting your connection if you wish to see all of the details">>} in 'Elixir.Keyword':'fetch!'/2 line 399 in 'Elixir.Connection':enter_stop/5 line 686
2020-06-06 22:02:30.338 [error] <0.663.0> CRASH REPORT Process <0.663.0> with 0 neighbours exited with reason: #{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError',message => <<"connect raised KeyError exception: key :database not found. The exception details are hidden, as they may contain sensitive data such as database credentials. You may set :show_sensitive_data_on_connection_error to true when starting your connection if you wish to see all of the details">>} in 'Elixir.Keyword':'fetch!'/2 line 399 in 'Elixir.Connection':enter_stop/5 line 686
2020-06-06 22:02:30.338 [error] <0.639.0> gen_server <0.639.0> terminated with reason: #{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError',message => <<"connect raised KeyError exception: key :database not found. The exception details are hidden, as they may contain sensitive data such as database credentials. You may set :show_sensitive_data_on_connection_error to true when starting your connection if you wish to see all of the details">>} in 'Elixir.Keyword':'fetch!'/2 line 399
2020-06-06 22:02:30.338 [error] <0.664.0> CRASH REPORT Process <0.664.0> with 0 neighbours exited with reason: #{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError',message => <<"connect raised KeyError exception: key :database not found. The exception details are hidden, as they may contain sensitive data such as database credentials. You may set :show_sensitive_data_on_connection_error to true when starting your connection if you wish to see all of the details">>} in 'Elixir.Keyword':'fetch!'/2 line 399 in 'Elixir.Connection':enter_stop/5 line 686
2020-06-06 22:02:30.338 [error] <0.673.0> gen_server <0.673.0> terminated with reason: #{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError',message => <<"connect raised KeyError exception: key :database not found. The exception details are hidden, as they may contain sensitive data such as database credentials. You may set :show_sensitive_data_on_connection_error to true when starting your connection if you wish to see all of the details">>} in 'Elixir.Keyword':'fetch!'/2 line 399
2020-06-06 22:02:30.339 [error] <0.640.0> gen_server <0.640.0> terminated with reason: #{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError',message => <<"connect raised KeyError exception: key :database not found. The exception details are hidden, as they may contain sensitive data such as database credentials. You may set :show_sensitive_data_on_connection_error to true when starting your connection if you wish to see all of the details">>} in 'Elixir.Keyword':'fetch!'/2 line 399
2020-06-06 22:02:30.339 [error] <0.641.0> gen_server <0.641.0> terminated with reason: #{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError',message => <<"connect raised KeyError exception: key :database not found. The exception details are hidden, as they may contain sensitive data such as database credentials. You may set :show_sensitive_data_on_connection_error to true when starting your connection if you wish to see all of the details">>} in 'Elixir.Keyword':'fetch!'/2 line 399
2020-06-06 22:02:30.339 [error] <0.642.0> gen_server <0.642.0> terminated with reason: #{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError',message => <<"connect raised KeyError exception: key :database not found. The exception details are hidden, as they may contain sensitive data such as database credentials. You may set :show_sensitive_data_on_connection_error to true when starting your connection if you wish to see all of the details">>} in 'Elixir.Keyword':'fetch!'/2 line 399
2020-06-06 22:02:30.339 [error] <0.643.0> gen_server <0.643.0> terminated with reason: #{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError',message => <<"connect raised KeyError exception: key :database not found. The exception details are hidden, as they may contain sensitive data such as database credentials. You may set :show_sensitive_data_on_connection_error to true when starting your connection if you wish to see all of the details">>} in 'Elixir.Keyword':'fetch!'/2 line 399
2020-06-06 22:02:30.339 [error] <0.644.0> gen_server <0.644.0> terminated with reason: #{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError',message => <<"connect raised KeyError exception: key :database not found. The exception details are hidden, as they may contain sensitive data such as database credentials. You may set :show_sensitive_data_on_connection_error to true when starting your connection if you wish to see all of the details">>} in 'Elixir.Keyword':'fetch!'/2 line 399
2020-06-06 22:02:30.340 [error] <0.662.0> Supervisor {<0.662.0>,'Elixir.DBConnection.ConnectionPool.Pool'} had child {'Elixir.Postgrex.Protocol',<0.661.0>,5} started with 'Elixir.DBConnection.Connection':start_link('Elixir.Postgrex.Protocol', [{pool_index,5},{types,'Elixir.Postgrex.DefaultTypes'},{hostname,<<"localhost">>},{port,5432},{repo,...},...], <0.661.0>, #Ref<0.1871405841.752746497.194845>) at <0.667.0> exit with reason #{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError',message => <<"connect raised KeyError exception: key :database not found. The exception details are hidden, as they may contain sensitive data such as database credentials. You may set :show_sensitive_data_on_connection_error to true when starting your connection if you wish to see all of the details">>} in 'Elixir.Keyword':'fetch!'/2 line 399 in context child_terminated
2020-06-06 22:02:30.340 [error] <0.673.0> CRASH REPORT Process <0.673.0> with 0 neighbours exited with reason: #{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError',message => <<"connect raised KeyError exception: key :database not found. The exception details are hidden, as they may contain sensitive data such as database credentials. You may set :show_sensitive_data_on_connection_error to true when starting your connection if you wish to see all of the details">>} in 'Elixir.Keyword':'fetch!'/2 line 399 in 'Elixir.Connection':enter_stop/5 line 686
2020-06-06 22:02:30.340 [error] <0.672.0> CRASH REPORT Process <0.672.0> with 0 neighbours exited with reason: #{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError',message => <<"connect raised KeyError exception: key :database not found. The exception details are hidden, as they may contain sensitive data such as database credentials. You may set :show_sensitive_data_on_connection_error to true when starting your connection if you wish to see all of the details">>} in 'Elixir.Keyword':'fetch!'/2 line 399 in 'Elixir.Connection':enter_stop/5 line 686
2020-06-06 22:02:30.340 [error] <0.674.0> gen_server <0.674.0> terminated with reason: #{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError',message => <<"connect raised KeyError exception: key :database not found. The exception details are hidden, as they may contain sensitive data such as database credentials. You may set :show_sensitive_data_on_connection_error to true when starting your connection if you wish to see all of the details">>} in 'Elixir.Keyword':'fetch!'/2 line 399
2020-06-06 22:02:30.340 [error] <0.671.0> CRASH REPORT Process <0.671.0> with 0 neighbours exited with reason: #{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError',message => <<"connect raised KeyError exception: key :database not found. The exception details are hidden, as they may contain sensitive data such as database credentials. You may set :show_sensitive_data_on_connection_error to true when starting your connection if you wish to see all of the details">>} in 'Elixir.Keyword':'fetch!'/2 line 399 in 'Elixir.Connection':enter_stop/5 line 686
2020-06-06 22:02:30.340 [error] <0.641.0> CRASH REPORT Process <0.641.0> with 0 neighbours exited with reason: #{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError',message => <<"connect raised KeyError exception: key :database not found. The exception details are hidden, as they may contain sensitive data such as database credentials. You may set :show_sensitive_data_on_connection_error to true when starting your connection if you wish to see all of the details">>} in 'Elixir.Keyword':'fetch!'/2 line 399 in 'Elixir.Connection':enter_stop/5 line 686
2020-06-06 22:02:30.340 [error] <0.668.0> CRASH REPORT Process <0.668.0> with 0 neighbours exited with reason: #{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError',message => <<"connect raised KeyError exception: key :database not found. The exception details are hidden, as they may contain sensitive data such as database credentials. You may set :show_sensitive_data_on_connection_error to true when starting your connection if you wish to see all of the details">>} in 'Elixir.Keyword':'fetch!'/2 line 399 in 'Elixir.Connection':enter_stop/5 line 686
2020-06-06 22:02:30.341 [error] <0.666.0> CRASH REPORT Process <0.666.0> with 0 neighbours exited with reason: #{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError',message => <<"connect raised KeyError exception: key :database not found. The exception details are hidden, as they may contain sensitive data such as database credentials. You may set :show_sensitive_data_on_connection_error to true when starting your connection if you wish to see all of the details">>} in 'Elixir.Keyword':'fetch!'/2 line 399 in 'Elixir.Connection':enter_stop/5 line 686
2020-06-06 22:02:30.341 [error] <0.645.0> gen_server <0.645.0> terminated with reason: #{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError',message => <<"connect raised KeyError exception: key :database not found. The exception details are hidden, as they may contain sensitive data such as database credentials. You may set :show_sensitive_data_on_connection_error to true when starting your connection if you wish to see all of the details">>} in 'Elixir.Keyword':'fetch!'/2 line 399
2020-06-06 22:02:30.341 [error] <0.650.0> gen_server <0.650.0> terminated with reason: #{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError',message => <<"connect raised KeyError exception: key :database not found. The exception details are hidden, as they may contain sensitive data such as database credentials. You may set :show_sensitive_data_on_connection_error to true when starting your connection if you wish to see all of the details">>} in 'Elixir.Keyword':'fetch!'/2 line 399
2020-06-06 22:02:30.341 [error] <0.646.0> gen_server <0.646.0> terminated with reason: #{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError',message => <<"connect raised KeyError exception: key :database not found. The exception details are hidden, as they may contain sensitive data such as database credentials. You may set :show_sensitive_data_on_connection_error to true when starting your connection if you wish to see all of the details">>} in 'Elixir.Keyword':'fetch!'/2 line 399
2020-06-06 22:02:30.341 [error] <0.651.0> gen_server <0.651.0> terminated with reason: #{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError',message => <<"connect raised KeyError exception: key :database not found. The exception details are hidden, as they may contain sensitive data such as database credentials. You may set :show_sensitive_data_on_connection_error to true when starting your connection if you wish to see all of the details">>} in 'Elixir.Keyword':'fetch!'/2 line 399
2020-06-06 22:02:30.341 [error] <0.652.0> gen_server <0.652.0> terminated with reason: #{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError',message => <<"connect raised KeyError exception: key :database not found. The exception details are hidden, as they may contain sensitive data such as database credentials. You may set :show_sensitive_data_on_connection_error to true when starting your connection if you wish to see all of the details">>} in 'Elixir.Keyword':'fetch!'/2 line 399
2020-06-06 22:02:30.341 [error] <0.653.0> gen_server <0.653.0> terminated with reason: #{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError',message => <<"connect raised KeyError exception: key :database not found. The exception details are hidden, as they may contain sensitive data such as database credentials. You may set :show_sensitive_data_on_connection_error to true when starting your connection if you wish to see all of the details">>} in 'Elixir.Keyword':'fetch!'/2 line 399
2020-06-06 22:02:30.342 [error] <0.662.0> Supervisor {<0.662.0>,'Elixir.DBConnection.ConnectionPool.Pool'} had child {'Elixir.Postgrex.Protocol',<0.661.0>,7} started with 'Elixir.DBConnection.Connection':start_link('Elixir.Postgrex.Protocol', [{pool_index,7},{types,'Elixir.Postgrex.DefaultTypes'},{hostname,<<"localhost">>},{port,5432},{repo,...},...], <0.661.0>, #Ref<0.1871405841.752746497.194845>) at <0.669.0> exit with reason #{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError',message => <<"connect raised KeyError exception: key :database not found. The exception details are hidden, as they may contain sensitive data such as database credentials. You may set :show_sensitive_data_on_connection_error to true when starting your connection if you wish to see all of the details">>} in 'Elixir.Keyword':'fetch!'/2 line 399 in context child_terminated
2020-06-06 22:02:30.342 [error] <0.675.0> gen_server <0.675.0> terminated with reason: #{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError',message => <<"connect raised KeyError exception: key :database not found. The exception details are hidden, as they may contain sensitive data such as database credentials. You may set :show_sensitive_data_on_connection_error to true when starting your connection if you wish to see all of the details">>} in 'Elixir.Keyword':'fetch!'/2 line 399
2020-06-06 22:02:30.342 [error] <0.654.0> gen_server <0.654.0> terminated with reason: #{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError',message => <<"connect raised KeyError exception: key :database not found. The exception details are hidden, as they may contain sensitive data such as database credentials. You may set :show_sensitive_data_on_connection_error to true when starting your connection if you wish to see all of the details">>} in 'Elixir.Keyword':'fetch!'/2 line 399
2020-06-06 22:02:30.342 [error] <0.655.0> gen_server <0.655.0> terminated with reason: #{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError',message => <<"connect raised KeyError exception: key :database not found. The exception details are hidden, as they may contain sensitive data such as database credentials. You may set :show_sensitive_data_on_connection_error to true when starting your connection if you wish to see all of the details">>} in 'Elixir.Keyword':'fetch!'/2 line 399
2020-06-06 22:02:30.342 [error] <0.656.0> gen_server <0.656.0> terminated with reason: #{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError',message => <<"connect raised KeyError exception: key :database not found. The exception details are hidden, as they may contain sensitive data such as database credentials. You may set :show_sensitive_data_on_connection_error to true when starting your connection if you wish to see all of the details">>} in 'Elixir.Keyword':'fetch!'/2 line 399
2020-06-06 22:02:30.342 [error] <0.657.0> gen_server <0.657.0> terminated with reason: #{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError',message => <<"connect raised KeyError exception: key :database not found. The exception details are hidden, as they may contain sensitive data such as database credentials. You may set :show_sensitive_data_on_connection_error to true when starting your connection if you wish to see all of the details">>} in 'Elixir.Keyword':'fetch!'/2 line 399
2020-06-06 22:02:30.343 [error] <0.658.0> gen_server <0.658.0> terminated with reason: #{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError',message => <<"connect raised KeyError exception: key :database not found. The exception details are hidden, as they may contain sensitive data such as database credentials. You may set :show_sensitive_data_on_connection_error to true when starting your connection if you wish to see all of the details">>} in 'Elixir.Keyword':'fetch!'/2 line 399
2020-06-06 22:02:30.343 [error] <0.659.0> gen_server <0.659.0> terminated with reason: #{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError',message => <<"connect raised KeyError exception: key :database not found. The exception details are hidden, as they may contain sensitive data such as database credentials. You may set :show_sensitive_data_on_connection_error to true when starting your connection if you wish to see all of the details">>} in 'Elixir.Keyword':'fetch!'/2 line 399
2020-06-06 22:02:30.343 [error] <0.636.0> Supervisor {<0.636.0>,'Elixir.DBConnection.ConnectionPool.Pool'} had child {'Elixir.Postgrex.Protocol',<0.635.0>,5} started with 'Elixir.DBConnection.Connection':start_link('Elixir.Postgrex.Protocol', [{pool_index,5},{types,'Elixir.Postgrex.DefaultTypes'},{hostname,<<"localhost">>},{port,5432},{repo,...},...], <0.635.0>, #Ref<0.1871405841.752746498.188707>) at <0.641.0> exit with reason #{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError',message => <<"connect raised KeyError exception: key :database not found. The exception details are hidden, as they may contain sensitive data such as database credentials. You may set :show_sensitive_data_on_connection_error to true when starting your connection if you wish to see all of the details">>} in 'Elixir.Keyword':'fetch!'/2 line 399 in context child_terminated
